server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - startup
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdv
    username: root
    password: 120312
    driver-class-name: com.mysql.cj.jdbc.Driver
  

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
    